name: Inspections

on:
  pull_request:

jobs:
  runPHPCSInspection:
    name: Run PHPCS inspection
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          tools: composer

      - name: Configure Composer
        run: composer config --no-interaction allow-plugins.dealerdirect/phpcodesniffer-composer-installer true

      - name: Install coding standards
        run: |
          composer require --dev squizlabs/php_codesniffer:^3.13
          composer require --dev wp-coding-standards/wpcs:^3.3
          composer require --dev dealerdirect/phpcodesniffer-composer-installer:^1.1

      - name: Show installed standards
        run: vendor/bin/phpcs -i

      - name: Run PHPCS inspection
        run: |
          vendor/bin/phpcs \
            --standard=WordPress \
            --ignore=.github/*,.wordpress-org/*,languages/* \
            .
