name: WPCS

on:
  pull_request:

jobs:
  phpcs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          tools: composer

      - name: Install dependencies
        run: |
          composer require --dev squizlabs/php_codesniffer
          composer require --dev wp-coding-standards/wpcs
          composer require --dev dealerdirect/phpcodesniffer-composer-installer

      - name: Run PHPCS
        run: |
          vendor/bin/phpcs --standard=WordPress .
